# What makes this pipeline run? When code gets checked into master
trigger:
- master

# The build agent will use the latest version of Windows, with all the latest stuff
pool:
  vmImage: 'windows-latest'

# Let's actually deploy our website
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      . .\newsnow.ps1
      newSNOWChange -SNOWuser admin -SNOWpass BcG1buYtOvM2 -instanceName dev65180 -CRShortDesc "Release: $(Build.SourceVersionMessage)" -CRFullDesc "Purple Savings and Loans webapp release to incorporate $(Build.SourceVersionMessage)" -CRJustificiation "Release Team" -CRPlan "Automated Release" -CRTestPlan "To be handed over to test team" -CRBackoutPlan "Rollback Commit" -CRSummaryNotes "By Geordie"


# Copy all the website files to the Azure storage account
- task: AzureFileCopy@3
  inputs:
    SourcePath: '.'
    azureSubscription: 'Visual Studio Professional(a7c01838-8c1a-463f-85db-9b46c88dd664)'
    Destination: 'AzureBlob'
    storage: 'psandlweb'
    ContainerName: '$web'

# Output what we just built, for safe keeping
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Published build with $(Build.SourceVersionMessage)"'